#!/bin/bash

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

main() {
    cd "$root"

    if [[ ! -e node_modules ]]; then
        npm i 'docco@0.7.0'
        (
            cd node_modules/docco/resources
            patch_data | patch languages.json
        )
    fi

    export PATH="$PATH:node_modules/.bin"
    docco config/bash/bashrc.sh
    docco config/vim/vimrc.vim
}

patch_data() {
    cat << 'END'
--- languages.json      2015-02-03 16:12:17.000000000 +0000
+++ languages.json2     2017-06-30 22:53:42.010888623 +0100
@@ -69,6 +69,7 @@
   ".vbs":         {"name": "vbscript", "symbol": "'"},
   ".vert":        {"name": "glsl", "symbol": "//"},
   ".vhdl":        {"name": "vhdl", "symbol": "--"},
+  ".vim":         {"name": "vim", "symbol": "\""},
   ".r":           {"name": "r", "symbol": "#"},
   ".rc":          {"name": "rust", "symbol": "//"},
   ".rs":          {"name": "rust", "symbol": "//"},
END
}

main
