#!/bin/bash

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

main() {
    cd "$root"
    npm i docco
    export PATH="$PATH:node_modules/.bin"
    docco config/bash/bashrc.sh
    docco config/vim/vimrc.vim
}

main
